# Pre-commit
# @see http://pre-commit.com/
default_stages:
  - "pre-commit"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace # Removes trailing whitespaces
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
      - id: check-yaml # Loads all yaml files to verify syntax
      - id: check-added-large-files # Prevents giant files from being committed (default=500kB)
      - id: debug-statements # Removes debug statements which should never be in production

  # Python code formatter
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        additional_dependencies:
          - "click==8.1.3" # Required in order for black to run
      - id: black-jupyter

  # Run black on python code blocks in documentation files
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - "black==21.12b0"

  # Sort your imports
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.5
  #   hooks:
  #     - id: isort
  #       name: isort (python)

  # # Toolkit for checking your code base against coding style (PEP8), programming errors and check cyclomatic complexity
  # - repo: https://github.com/pycqa/flake8
  #   rev: 5.0.4
  #   hooks:
  #     - id: flake8
  #       additional_dependencies:
  #         # - "flake8-bandit==2.1.2"
  #         - "flake8-bugbear==22.1.11"
  #         - "flake8-docstrings==1.6.0"
  #         # - "bandit==1.7.2" # Required in order for flake8 to run

  # Static type checker
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.960
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         [
  #           "types-PyYaml",
  #           "types-python-dateutil",
  #           "types-requests",
  #           types-retry,
  #         ]

  # SQL linter that supports many dialects
  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 0.13.2
  #   hooks:
  #     - id: sqlfluff-lint
  #       args: ["--dialect", "sparksql"]

  # A systems hook that just runs php -l against stage files that have the .php extension
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-lint-all

  # validate Markdown / RST files
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter

  # Notebook remove results
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
